"""
PDF Report Generator for Universal AutoML Platform.
Generates a clean one-page+ summary of model results, charts, and feature importance.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
import io
from datetime import datetime


def generate_pdf_report(
    dataset_name, task_type, best_model_name, report_df,
    target_col, n_rows, n_cols, chart_image_paths=None
):
    """
    Builds a PDF report and returns bytes ready for st.download_button.

    chart_image_paths: list of file paths to PNG charts to embed (optional)
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=2 * cm, rightMargin=2 * cm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Title'],
        fontSize=22, textColor=colors.HexColor('#0d1325'),
        alignment=TA_CENTER, spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle', parent=styles['Normal'],
        fontSize=11, textColor=colors.HexColor('#555555'),
        alignment=TA_CENTER, spaceAfter=20
    )
    heading_style = ParagraphStyle(
        'HeadingStyle', parent=styles['Heading2'],
        fontSize=14, textColor=colors.HexColor('#00897B'),
        spaceBefore=16, spaceAfter=8
    )
    body_style = styles['Normal']

    elements = []

    elements.append(Paragraph("⚙️ Universal AutoML Engine", title_style))
    elements.append(Paragraph("Model Performance Report", subtitle_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        ParagraphStyle('date', parent=body_style, alignment=TA_CENTER, fontSize=9, textColor=colors.grey)
    ))
    elements.append(Spacer(1, 16))

    # Dataset summary
    elements.append(Paragraph("Dataset Summary", heading_style))
    summary_data = [
        ["Dataset", dataset_name],
        ["Rows", str(n_rows)],
        ["Columns", str(n_cols)],
        ["Target Column", target_col],
        ["Task Type", task_type],
    ]
    summary_table = Table(summary_data, colWidths=[5 * cm, 9 * cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f2f6')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#222222')),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 12))

    # Best model
    elements.append(Paragraph("Winning Model", heading_style))
    elements.append(Paragraph(
        f"<b>{best_model_name}</b> was selected as the best performing model.",
        body_style
    ))
    elements.append(Spacer(1, 12))

    # Results table
    elements.append(Paragraph("Model Comparison", heading_style))
    display_cols = [c for c in report_df.columns if c != 'Tuned']
    table_data = [display_cols] + report_df[display_cols].round(4).astype(str).values.tolist()
    results_table = Table(table_data, repeatRows=1)
    results_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#00897B')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7f7f7')]),
    ]))
    elements.append(results_table)
    elements.append(Spacer(1, 16))

    # Charts
    if chart_image_paths:
        elements.append(Paragraph("Visual Analysis", heading_style))
        for path in chart_image_paths:
            try:
                elements.append(Image(path, width=14 * cm, height=8 * cm))
                elements.append(Spacer(1, 10))
            except Exception:
                pass

    # Footer
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by Universal AutoML Engine — github.com/moinudheen17/universal-automl-platform",
        ParagraphStyle('footer', parent=body_style, alignment=TA_CENTER, fontSize=8, textColor=colors.grey)
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
